In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r'C:\Users\PC\Desktop\محرومیت\data\labour_force_all_2.csv',low_memory=False)

In [6]:
df.shape

(1678970, 43)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1678970 entries, 0 to 1678969
Data columns (total 43 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   pkey              1678970 non-null  int64
 1   NobatAmargiri     1678970 non-null  int64
 2   F2_D03            1678970 non-null  object
 3   F2_D04            1678970 non-null  int64
 4   F2_D05            1470585 non-null  object
 5   F2_D06            1639613 non-null  object
 6   F2_D07            1678738 non-null  float64
 7   F2_D15            1678970 non-null  int64
 8   F2_D16            1678970 non-null  int64
 9   F2_D17            1438758 non-null  float64
 10  F2_D18            649524 non-null   object
 11  F2_D19            1678970 non-null  object
 12  F3_D01            1678970 non-null  int64
 13  F3_D02            1188238 non-null  float64
 14  F3_D03            1176432 non-null  float64
 15  F3_D04            1147190 non-null  float64
 16  F3_D05            1144485 non-null  float64
 17  F3_D06            1140088 non-null  float64
 18  F3_D07            17795 non-null    object
 19  F3_D09            556677 non-null   object
 20  F3_D11            556677 non-null   float64
 21  F3_D13            556677 non-null   object
 22  F3_D24            556667 non-null   object
 23  F3_D31            1122293 non-null  float64
 24  F3_D33            1073681 non-null  float64
 25  F3_D37MAH         27294 non-null    float64
 26  F3_D38            27284 non-null    object
 27  F3_D47            1073315 non-null  float64
 28  F3_D49            1678738 non-null  float64
 29  IW_Yearly         1678970 non-null  float64
 30  ActivityStatus    1678970 non-null  int64
 31  year              1678970 non-null  int64
 32  household_number  1678970 non-null  int64
 33  cluster_number    1678970 non-null  int64
 34  urban_rural       1678970 non-null  int64
 35  province_code     1678970 non-null  int64
 36  sample_year       1678970 non-null  int64
 37  education_group   648764 non-null   object
 38  dep_sex           1678970 non-null  int64
 39  dep_urban_rural   1678970 non-null  int64
 40  dep_edu           1678970 non-null  int64
 41  dep_age_group     1678970 non-null  int64
 42  deprived          1678970 non-null  int64
dtypes: float64(14), int64(18), object(11)
memory usage: 550.8+ MB

pkey                  int64
NobatAmargiri         int64
F2_D03               object
F2_D04                int64
F2_D05               object
F2_D06               object
F2_D07              float64
F2_D15                int64
F2_D16                int64
F2_D17              float64
F2_D18               object
F2_D19               object
F3_D01                int64
F3_D02              float64
F3_D03              float64
F3_D04              float64
F3_D05              float64
F3_D06              float64
F3_D07               object
F3_D09               object
F3_D11              float64
F3_D13               object
F3_D24               object
F3_D31              float64
F3_D33              float64
F3_D37MAH           float64
F3_D38               object
F3_D47              float64
F3_D49              float64
IW_Yearly           float64
ActivityStatus        int64
year                  int64
household_number      int64
cluster_number        int64
urban_rural           int64
province_code         int64
sample_year           int64
education_group      object
dep_sex               int64
dep_urban_rural       int64
dep_edu               int64
dep_age_group         int64
deprived              int64
dtype: object

In [13]:
df.head(10)

,pkey,NobatAmargiri,F2_D03,F2_D04,F2_D05,F2_D06,F2_D07,F2_D15,F2_D16,F2_D17,...,cluster_number,urban_rural,province_code,sample_year,education_group,dep_sex,dep_urban_rural,dep_edu,dep_age_group,deprived
0,125103261,3,1,1,03,47,54.0,2,1,8.0,...,32,1,25,1,Health and Welfare,0,0,0,3,0
1,125103261,3,2,2,03,58,43.0,2,1,7.0,...,32,1,25,1,Health and Welfare,1,0,0,3,0
2,125103261,3,3,2,03,80,21.0,1,1,6.0,...,32,1,25,1,Services,1,0,0,1,0
3,125103261,3,3,1,08,85,16.0,1,1,3.0,...,32,1,25,1,Natural Sciences,0,0,1,1,0
4,125103262,2,1,1,09,71,29.0,2,1,4.0,...,32,1,25,1,Engineering and Manufacturing,0,0,0,2,0
5,125103262,2,2,2,06,73,27.0,2,1,2.0,...,32,1,25,1,NaN,1,0,1,2,1
6,125103262,3,1,1,09,71,30.0,2,1,4.0,...,32,1,25,1,Engineering and Manufacturing,0,0,0,2,0
7,125103262,3,2,2,06,73,28.0,2,1,2.0,...,32,1,25,1,NaN,1,0,1,2,1
8,125103263,2,1,1,01,62,39.0,2,1,1.0,...,32,1,25,1,NaN,0,0,1,2,1
9,125103263,2,2,2,06,62,38.0,2,1,2.0,...,32,1,25,1,NaN,1,0,1,2,1

In [14]:
df.tail(10)

,pkey,NobatAmargiri,F2_D03,F2_D04,F2_D05,F2_D06,F2_D07,F2_D15,F2_D16,F2_D17,...,cluster_number,urban_rural,province_code,sample_year,education_group,dep_sex,dep_urban_rural,dep_edu,dep_age_group,deprived
1678960,330112679,3,3,1,06,78,24.0,2,1,2.0,...,126,1,30,3,NaN,0,0,1,1,0
1678961,330112679,4,1,1,01,48,55.0,2,1,2.0,...,126,1,30,3,NaN,0,0,1,4,0
1678962,330112679,4,2,2,02,51,52.0,2,1,1.0,...,126,1,30,3,NaN,1,0,1,3,1
1678963,330112679,4,3,1,06,78,25.0,2,1,4.0,...,126,1,30,3,Business and Law,0,0,0,2,0
1678964,330112680,3,1,1,04,58,45.0,2,1,4.0,...,126,1,30,3,Arts and Humanities,0,0,0,3,0
1678965,330112680,3,2,2,09,56,46.0,2,1,5.0,...,126,1,30,3,Arts and Humanities,1,0,0,3,1
1678966,330112680,3,3,1,04,83,20.0,1,1,6.0,...,126,1,30,3,ICT,0,0,0,1,0
1678967,330112680,3,3,1,04,89,14.0,1,1,2.0,...,126,1,30,3,NaN,0,0,1,1,0
1678968,330112680,4,1,1,04,58,45.0,2,1,4.0,...,126,1,30,3,Arts and Humanities,0,0,0,3,0
1678969,330112680,4,2,2,09,56,46.0,2,1,5.0,...,126,1,30,3,Arts and Humanities,1,0,0,3,1

In [16]:
df.describe()

,pkey,NobatAmargiri,F2_D04,F2_D07,F2_D15,F2_D16,F2_D17,F3_D01,F3_D02,F3_D03,...,household_number,cluster_number,urban_rural,province_code,sample_year,dep_sex,dep_urban_rural,dep_edu,dep_age_group,deprived
count,1.678970e+06,1.678970e+06,1.678970e+06,1.678738e+06,1.678970e+06,1.678970e+06,1.438758e+06,1.678970e+06,1.188238e+06,1.176432e+06,...,1.678970e+06,1.678970e+06,1.678970e+06,1.678970e+06,1.678970e+06,1.678970e+06,1.678970e+06,1.678970e+06,1.678970e+06,1.678970e+06
mean,2.135208e+08,2.530269e+00,1.503789e+00,3.963345e+01,1.808015e+00,1.143071e+00,2.948485e+00,1.707718e+00,1.990064e+00,1.975143e+00,...,7.365279e+01,8.392163e+01,1.381378e+00,1.465726e+01,1.987169e+00,5.037886e-01,3.813779e-01,6.524333e-01,2.457487e+00,4.703932e-01
std,8.219312e+07,1.113221e+00,4.999858e-01,1.871639e+01,3.938614e-01,3.501454e-01,1.871133e+00,4.548111e-01,9.918170e-02,1.556878e-01,...,1.206417e+01,4.982116e+01,4.857252e-01,8.984233e+00,8.165593e-01,4.999858e-01,4.857252e-01,4.761977e-01,1.094323e+00,4.991228e-01
min,1.001002e+08,1.000000e+00,1.000000e+00,1.000000e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,4.900000e+01,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
25%,1.222097e+08,2.000000e+00,1.000000e+00,2.500000e+01,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,...,6.500000e+01,4.200000e+01,1.000000e+00,7.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00
50%,2.141011e+08,3.000000e+00,2.000000e+00,3.900000e+01,2.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,...,7.400000e+01,8.200000e+01,1.000000e+00,1.400000e+01,2.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,0.000000e+00
75%,3.062184e+08,4.000000e+00,2.000000e+00,5.300000e+01,2.000000e+00,1.000000e+00,4.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,...,8.300000e+01,1.230000e+02,2.000000e+00,2.300000e+01,3.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,1.000000e+00
max,3.302180e+08,4.000000e+00,2.000000e+00,9.900000e+01,2.000000e+00,2.000000e+00,9.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,...,9.900000e+01,2.210000e+02,2.000000e+00,3.000000e+01,3.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.000000e+00,1.000000e+00

In [25]:
df['F2_D04'].value_counts().sort_values()

F2_D07
98.0       95
99.0      100
97.0      164
96.0      262
95.0      318
        ...
40.0    35700
35.0    36388
37.0    36504
36.0    36710
38.0    37208
Name: count, Length: 90, dtype: int64

In [24]:
df['F2_D07'].value_counts().sort_values()

F2_D07
98.0       95
99.0      100
97.0      164
96.0      262
95.0      318
        ...
40.0    35700
35.0    36388
37.0    36504
36.0    36710
38.0    37208
Name: count, Length: 90, dtype: int64

In [26]:
df['F2_D17'].value_counts().sort_values()

F2_D17
9.0       301
8.0      3535
7.0     43583
5.0     52006
3.0     66262
6.0    183006
4.0    301123
2.0    355800
1.0    433142
Name: count, dtype: int64

In [27]:
df['dep_sex'].value_counts().sort_values()

dep_sex
0    833124
1    845846
Name: count, dtype: int64

In [28]:
df['dep_urban_rural'].value_counts().sort_values()

dep_urban_rural
1     640322
0    1038648
Name: count, dtype: int64

In [29]:
df['dep_edu'].value_counts().sort_values()

dep_edu
0     583554
1    1095416
Name: count, dtype: int64

In [30]:
df['deprived'].value_counts().sort_values()

deprived
1    789776
0    889194
Name: count, dtype: int64

In [31]:
df['dep_age_group'].value_counts().sort_values()

dep_age_group
4    379941
1    417023
3    425248
2    456758
Name: count, dtype: int64

In [34]:
df_new = df[df['F2_D07'] >= 15 ]

In [35]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1509233 entries, 0 to 1678969
Data columns (total 43 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   pkey              1509233 non-null  int64
 1   NobatAmargiri     1509233 non-null  int64
 2   F2_D03            1509233 non-null  object
 3   F2_D04            1509233 non-null  int64
 4   F2_D05            1320423 non-null  object
 5   F2_D06            1475087 non-null  object
 6   F2_D07            1509233 non-null  float64
 7   F2_D15            1509233 non-null  int64
 8   F2_D16            1509233 non-null  int64
 9   F2_D17            1270273 non-null  float64
 10  F2_D18            648995 non-null   object
 11  F2_D19            1509233 non-null  object
 12  F3_D01            1509233 non-null  int64
 13  F3_D02            1019012 non-null  float64
 14  F3_D03            1007248 non-null  float64
 15  F3_D04            978720 non-null   float64
 16  F3_D05            976032 non-null   float64
 17  F3_D06            971710 non-null   float64
 18  F3_D07            17792 non-null    object
 19  F3_D09            555315 non-null   object
 20  F3_D11            555315 non-null   float64
 21  F3_D13            555315 non-null   object
 22  F3_D24            555305 non-null   object
 23  F3_D31            953918 non-null   float64
 24  F3_D33            905407 non-null   float64
 25  F3_D37MAH         27270 non-null    float64
 26  F3_D38            27260 non-null    object
 27  F3_D47            905042 non-null   float64
 28  F3_D49            1509233 non-null  float64
 29  IW_Yearly         1509233 non-null  float64
 30  ActivityStatus    1509233 non-null  int64
 31  year              1509233 non-null  int64
 32  household_number  1509233 non-null  int64
 33  cluster_number    1509233 non-null  int64
 34  urban_rural       1509233 non-null  int64
 35  province_code     1509233 non-null  int64
 36  sample_year       1509233 non-null  int64
 37  education_group   648235 non-null   object
 38  dep_sex           1509233 non-null  int64
 39  dep_urban_rural   1509233 non-null  int64
 40  dep_edu           1509233 non-null  int64
 41  dep_age_group     1509233 non-null  int64
 42  deprived          1509233 non-null  int64
dtypes: float64(14), int64(18), object(11)
memory usage: 506.6+ MB

In [36]:
df_new.drop(columns=['F3_D37MAH','F3_D38','F3_D07',])

,pkey,NobatAmargiri,F2_D03,F2_D04,F2_D05,F2_D06,F2_D07,F2_D15,F2_D16,F2_D17,...,cluster_number,urban_rural,province_code,sample_year,education_group,dep_sex,dep_urban_rural,dep_edu,dep_age_group,deprived
0,125103261,3,1,1,03,47,54.0,2,1,8.0,...,32,1,25,1,Health and Welfare,0,0,0,3,0
1,125103261,3,2,2,03,58,43.0,2,1,7.0,...,32,1,25,1,Health and Welfare,1,0,0,3,0
2,125103261,3,3,2,03,80,21.0,1,1,6.0,...,32,1,25,1,Services,1,0,0,1,0
3,125103261,3,3,1,08,85,16.0,1,1,3.0,...,32,1,25,1,Natural Sciences,0,0,1,1,0
4,125103262,2,1,1,09,71,29.0,2,1,4.0,...,32,1,25,1,Engineering and Manufacturing,0,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678964,330112680,3,1,1,04,58,45.0,2,1,4.0,...,126,1,30,3,Arts and Humanities,0,0,0,3,0
1678965,330112680,3,2,2,09,56,46.0,2,1,5.0,...,126,1,30,3,Arts and Humanities,1,0,0,3,1
1678966,330112680,3,3,1,04,83,20.0,1,1,6.0,...,126,1,30,3,ICT,0,0,0,1,0
1678968,330112680,4,1,1,04,58,45.0,2,1,4.0,...,126,1,30,3,Arts and Humanities,0,0,0,3,0
1678969,330112680,4,2,2,09,56,46.0,2,1,5.0,...,126,1,30,3,Arts and Humanities,1,0,0,3,1

In [40]:
df_new.to_csv(r'C:\Users\PC\Desktop\محرومیت\data\labour_force_all_3.csv')